version: '3.8'

services:
  examcraft-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: examcraft-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=localhost
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - examcraft-network

networks:
  examcraft-network:
    driver: bridge
