version: '3.8'

services:
  examcraft-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: examcraft-backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5001/api/v1/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - examcraft-network

networks:
  examcraft-network:
    driver: bridge 